ENTER_CHOICE_INPUT_TEXT = "Enter choice: "
ENTER_PASSWORD_TEXT = "Enter a new password for the MetaMask wallet extension: "
CONFIRM_PASSWORD_TEXT = "Confirm extension password: "
PASSWORD_IS_EMPTY_TEXT = "Password cannot be empty"
PASSWORD_NOT_IS_EMPTY_TEXT = "Password must be at least 8 characters long"
NOT_PASSWORD_CONFIRMED_TEXT = "Passwords do not match"
